services:
  server:
    image: python:3.11
    copy: server
    command:
      - pip install -r requirements.txt
      - python manage.py makemigrations
      - python manage.py migrate
      - python manage.py runserver
    port: 8080:8080
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DB_TYPE=postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    working_dir: ./server
    networks:
      - net

  bot:
    image: python:3.11
    command:
      - python bot.py
    port: 8000:8000
    depends_on:
      - server
    working_dir: ./bot
    networks:
      - net

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_database:/var/lib/postgresql/data

  volumes:
    postgres_database:

  networks:
    net: