# Generated by Django 5.0.7 on 2024-07-19 04:45

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('E:/Python/BusinesscardChatBot/server/static/media/photos/workers')),
        ),
    ]
