# Generated by Django 5.0.7 on 2024-07-18 13:23

import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('short_info', models.TextField()),
                ('full_info', models.TextField()),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be exactly 10 digits')])),
                ('address', models.TextField()),
                ('logo', models.ImageField(upload_to=pathlib.PureWindowsPath('E:/Python/AdministratorChatBot/server/static/media/photos'))),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
