# Generated by Django 5.0.7 on 2024-07-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_confirmed',
        ),
    ]
